[package]
name = "nazeka_epwing_converter"
version = "0.1.0"
authors = ["wareya <wareya@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
regex = "1.1"
text_io = "0.1.7"
lazy_static = "1"
